/**
 * FFmpeg command generator — reads slide-timings.json and produces a
 * build-video.sh script with xfade transitions between slides.
 */

const fs = require('fs');
const path = require('path');
const chalk = require('chalk');

/**
 * Generate the FFmpeg shell script that assembles the final video.
 */
function generateFfmpegScript(config) {
  const timingsPath = path.join(config.outputDir, 'slide-timings.json');
  if (!fs.existsSync(timingsPath)) {
    throw new Error(`slide-timings.json not found in ${config.outputDir}. Run the timings step first.`);
  }

  const timings = JSON.parse(fs.readFileSync(timingsPath, 'utf-8'));
  const n = timings.length;
  const xfade = config.transition_duration;
  const transition = config.transition;

  // Use annotated slides if available
  const slidesDir = fs.existsSync(config.annotatedDir) &&
    fs.readdirSync(config.annotatedDir).some(f => f.endsWith('.png'))
    ? config.annotatedDir
    : config.slidesDir;

  const chunksDir = config.chunksDir;

  // Optional click sound
  const clickPath = config.click_sound
    ? path.resolve(config.projectDir, config.click_sound)
    : null;
  const hasClick = clickPath && fs.existsSync(clickPath);

  // Optional background music
  const musicPath = config.background_music
    ? path.resolve(config.projectDir, config.background_music)
    : null;
  const hasMusic = musicPath && fs.existsSync(musicPath);
  const musicVolume = config.music_volume || 0.15;

  let cmd = '#!/usr/bin/env bash\nset -euo pipefail\n\n';
  cmd += `# Auto-generated by script-to-video\n`;
  cmd += `# Slides: ${n}, transition: ${transition} (${xfade}s), crf: ${config.crf}\n\n`;

  // Build ffmpeg command
  cmd += 'ffmpeg -y \\\n';

  // Video inputs — loop each slide for its duration
  timings.forEach((t, i) => {
    const padded = String(i).padStart(2, '0');
    const slidePath = path.join(slidesDir, `slide-${padded}.png`);
    cmd += `  -loop 1 -t ${t.slide_duration.toFixed(3)} -i "${slidePath}" \\\n`;
  });

  // Audio inputs
  timings.forEach(t => {
    cmd += `  -i "${path.join(chunksDir, t.chunk)}" \\\n`;
  });

  // Tail silence
  cmd += `  -i "${path.join(chunksDir, 'tail-silence.wav')}" \\\n`;

  // Click sound (optional)
  if (hasClick) {
    cmd += `  -i "${clickPath}" \\\n`;
  }

  // Background music (optional)
  if (hasMusic) {
    cmd += `  -stream_loop -1 -i "${musicPath}" \\\n`;
  }

  cmd += '  -filter_complex "\n';

  // Video xfade chain
  if (n === 1) {
    cmd += '    [0:v]null[video];\n';
  } else {
    let offset = 0;
    for (let i = 0; i < n - 1; i++) {
      const inLabel = i === 0 ? '[0:v]' : `[v${i}]`;
      const outLabel = i === n - 2 ? '[video]' : `[v${i + 1}]`;
      offset += timings[i].slide_duration - xfade;
      cmd += `    ${inLabel}[${i + 1}:v]xfade=transition=${transition}:duration=${xfade}:offset=${offset.toFixed(3)}${outLabel};\n`;
    }
  }

  // Audio concat
  const audioInputs = timings.map((_, i) => `[${n + i}:a]`).join('');
  const tailIdx = n + timings.length;
  cmd += `    ${audioInputs}[${tailIdx}:a]concat=n=${n + 1}:v=0:a=1[narration];\n`;

  // Mix narration with optional click sound and/or background music
  let nextIdx = tailIdx + 1;
  let currentAudioLabel = 'narration';

  if (hasClick) {
    const clickIdx = nextIdx++;
    cmd += `    [${currentAudioLabel}][${clickIdx}:a]amix=inputs=2:normalize=0[narr_click];\n`;
    currentAudioLabel = 'narr_click';
  }

  if (hasMusic) {
    const musicIdx = nextIdx++;
    // Lower the music volume and mix it under the narration
    cmd += `    [${musicIdx}:a]volume=${musicVolume}[bgmusic];\n`;
    cmd += `    [${currentAudioLabel}][bgmusic]amix=inputs=2:duration=shortest:normalize=0[audio]\n`;
  } else if (currentAudioLabel !== 'narration') {
    // Rename the click-mixed output to [audio]
    cmd = cmd.replace(`[${currentAudioLabel}];\n`, `[audio];\n`);
  } else {
    cmd += `    [narration]anull[audio]\n`;
  }

  cmd += '  " \\\n';
  cmd += '  -map "[video]" -map "[audio]" \\\n';
  cmd += `  -c:v libx264 -preset ${config.preset} -crf ${config.crf} -pix_fmt yuv420p \\\n`;
  cmd += `  -c:a aac -b:a ${config.audio_bitrate} \\\n`;
  cmd += `  "${config.outputPath}"\n`;

  const scriptPath = path.join(config.outputDir, 'build-video.sh');
  fs.writeFileSync(scriptPath, cmd);
  fs.chmodSync(scriptPath, 0o755);

  console.log(chalk.green(`  + Generated build-video.sh (${n} slides, ${transition} transition)`));
  return scriptPath;
}

module.exports = { generateFfmpegScript };
